version: 1
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:../02%20-%20dockerfile/Dockerfile
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
      - deploy:
          name: Publish application to docker hub
          command: |
            docker login -e provectus@7pz.ru -u 7pzru a@Rb8bxcL9jDMA6@
            docker tag dockerapp_dockerapp $7pzru/dockerapp:latest
            docker push 7pzru/dockerapp:5HGqrVHl1HmmqaGiz1EXSJ/OpfJIhW6IKSPOKJybOdI
            docker push 7pzru/dockerapp:latest